### ISSUE TITLE
Error with Make

### ISSUE THREAD

**Issue by ARHLANE** [NewProggie/Particle-Filter#1]
989/5000
Hello
Thank you for charing your code
I tried to compile your project I may have received the following error
[50%] Building CXX object CMakeFiles / main.dir / src / adaboostDetect.cpp.o
/home/arhlane/Particle-Filter/src/colorFeatures.cpp: In member function 'histogram * colorFeatures :: comHistogramHSV (IplImage *, int)':
/home/arhlane/Particle-Filter/src/colorFeatures.cpp:53:45: error: 'cvCvtPixToPlane' was not declared in this scope
          CvCvtPixToPlane (img, h, s, v, null);
                                              ^
[66%] Building CXX object CMakeFiles / main.dir / src / particleFilter.cpp.o
[83%] Building CXX object CMakeFiles / main.dir / src / tracker.cpp.o
Make [2]: *** [CMakeFiles / main.dir / src / colorFeatures.cpp.o] Error 1
Make [2]: *** Waiting for unfinished jobs ....
Make [1]: *** [CMakeFiles / main.dir / all] Error 2

**Comment by NewProggie** [comment]
You're using a newer version of OpenCV than the code was using back then. Note that the code in this project is more than five years old.

Try substituting the function `cvCvtPixToPlane()` with `cvSplit()`

**Comment by ARHLANE** [comment]
thank you for your reply
I run the code (FPS too slow)
